custom:
  cors:
    allowedOrigins: "http://localhost:63344"

server:
  port: ${SERVER_PORT:9797}

logging:
  level:
    org:
      springframework.security: DEBUG
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: "false"
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    jdbc:
      time_zone: UTC
    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    jdbc:
      time_zone: UTC
    open-in-view: false

---
